name: Test and Build Image for Docker

on: [push]

env:
  DOCKER_NAME: kaw393939/module1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.9
    - name: Install dependencies
      run: |
        python -m pip install pylint
        python -m pip install pytest
    - name: Lint with pylint
      run: |
        python -m pylint app/__init__.py
    - name: Test with pytest
      run: |
        python -m pytest
    - name: Build and push Docker image
      if: success()
      uses: docker/build-push-action@v2
      with:
        context: .
        tags: ${{ env.DOCKER_NAME }}:${{ env.GITHUB_SHA }}
        push: true
        login: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}